const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const defaultCourses=[{id:'cognitive',name:'认知心理学',open:true,lessons:[{id:'attention',name:'注意的选择机制'},{id:'memory',name:'工作记忆模型'},{id:'language',name:'语言加工'}]},{id:'measurement',name:'心理测量',open:false,lessons:[]},{id:'experimental',name:'实验心理学',open:false,lessons:[]}];
const state={recording:false,paused:false,seconds:0,recordedDuration:0,timer:null,mediaRecorder:null,stream:null,chunks:[],recognition:null,currentCourse:'cognitive',currentLesson:'attention',courses:JSON.parse(localStorage.getItem('keji-courses')||'null')||defaultCourses,playbackUrl:null};
const editor=$('#noteEditor'), timerEl=$('#timer'), recordBtn=$('#recordBtn'), pauseBtn=$('#pauseBtn'), stopBtn=$('#stopBtn'),audio=$('#audioPlayback'),seek=$('#audioSeek');
let savedEditorRange=null;
const pad=n=>String(n).padStart(2,'0');
const formatTime=s=>`${pad(Math.floor(s/3600))}:${pad(Math.floor(s%3600/60))}:${pad(s%60)}`;
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2200)}
function setSaved(label='已保存'){ $('#saveText').textContent=label; }
function updateCount(){editor.querySelectorAll('script,style').forEach(n=>n.remove());const text=editor.innerText.trim();$('#wordCount').textContent=`${text.length} 字`;try{localStorage.setItem(`keji-notes-${state.currentLesson}`,editor.innerHTML);setSaved('已保存')}catch(e){setSaved('图片过大，未保存');toast('本地空间不足，请缩小或减少图片')}}
function captureEditorRange(){const selection=getSelection();if(selection?.rangeCount&&editor.contains(selection.anchorNode))savedEditorRange=selection.getRangeAt(0).cloneRange()}
function restoreEditorRange(){const selection=getSelection();editor.focus();selection.removeAllRanges();if(savedEditorRange&&editor.contains(savedEditorRange.commonAncestorContainer)){selection.addRange(savedEditorRange);return}const range=document.createRange();range.selectNodeContents(editor);range.collapse(false);selection.addRange(range);savedEditorRange=range.cloneRange()}
function activeEditorElement(){const selection=getSelection(),node=selection?.anchorNode;return node?(node.nodeType===Node.ELEMENT_NODE?node:node.parentElement):null}
function activeBlock(){return activeEditorElement()?.closest('p,h2,h3,blockquote,li,td,th,div')||null}
function syncFormatToolbar(){const element=activeEditorElement(),block=activeBlock(),tag=block?.tagName?.toLowerCase();if(['p','h2','h3','blockquote'].includes(tag))$('#blockFormat').value=tag;const size=parseFloat(getComputedStyle(element||block||editor).fontSize);$('#fontSizeValue').textContent=Math.round(size||16)}
function renderNoteOutline(){editor.querySelectorAll('[data-outline-index]').forEach(node=>node.removeAttribute('data-outline-index'));const headings=[...editor.querySelectorAll('h2,h3')].filter(node=>node.textContent.trim());headings.forEach((node,index)=>node.dataset.outlineIndex=String(index));$('#noteOutline').innerHTML=headings.length?headings.map((node,index)=>`<button class="outline-item level-${node.tagName==='H2'?1:2}" type="button" data-outline-index="${index}" title="${esc(node.textContent.trim())}">${esc(node.textContent.trim())}</button>`).join(''):'<div class="note-outline-empty">还没有标题。选中一段文字，再设为一级或二级标题，它就会出现在这里。</div>'}
$('#outlineToggle').onclick=()=>{const panel=$('#noteOutline'),open=panel.hidden;panel.hidden=!open;$('#outlineToggle').setAttribute('aria-expanded',String(open));if(open)renderNoteOutline()};
$('#noteOutline').onclick=e=>{const button=e.target.closest('[data-outline-index]');if(!button)return;const target=editor.querySelector(`[data-outline-index="${button.dataset.outlineIndex}"]`);target?.scrollIntoView({behavior:'smooth',block:'center'});target?.classList.add('outline-flash');setTimeout(()=>target?.classList.remove('outline-flash'),1400);$('#noteOutline').hidden=true;$('#outlineToggle').setAttribute('aria-expanded','false')};
document.addEventListener('selectionchange',()=>{if(getSelection()?.anchorNode&&editor.contains(getSelection().anchorNode)){captureEditorRange();syncFormatToolbar()}});
editor.addEventListener('input',()=>{captureEditorRange();renderNoteOutline();setSaved('正在保存…');clearTimeout(editor._saveTimer);editor._saveTimer=setTimeout(updateCount,500)});
editor.addEventListener('keydown',e=>{if(e.key!=='Tab')return;e.preventDefault();captureEditorRange();const block=activeBlock();if(!block||block===editor)return;if(block.tagName==='LI'){document.execCommand(e.shiftKey?'outdent':'indent',false)}else{const current=parseInt(block.style.marginLeft||'0',10)||0;block.style.marginLeft=`${Math.max(0,Math.min(280,current+(e.shiftKey?-28:28)))}px`}captureEditorRange();updateCount()});
function insertHtml(html){restoreEditorRange();document.execCommand('insertHTML',false,html);captureEditorRange();updateCount()}
function safeFilename(value){return String(value||'课堂笔记').replace(/[\\/:*?"<>|]/g,'-').replace(/\s+/g,' ').trim().slice(0,70)||'课堂笔记'}
function downloadWord(){
  updateCount();
  const course=currentCourse()?.name||$('#courseName').textContent,lesson=currentLesson()?.name||$('#lessonTitle').textContent,copy=editor.cloneNode(true);
  copy.querySelectorAll('.image-tools,button,script,style').forEach(node=>node.remove());
  copy.querySelectorAll('[contenteditable]').forEach(node=>node.removeAttribute('contenteditable'));
  copy.querySelectorAll('.note-image').forEach(figure=>{figure.removeAttribute('style');const img=figure.querySelector('img');if(img){img.removeAttribute('style');img.setAttribute('width','560')}});
  const dateText=new Date().toLocaleDateString('zh-CN');
  const html=`<!DOCTYPE html><html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"><title>${esc(lesson)}</title><style>@page{margin:2.2cm}body{font-family:"Microsoft YaHei","SimSun",sans-serif;color:#20242c;line-height:1.75;font-size:12pt}h1{font-size:22pt;margin:0 0 6pt}h2{font-size:18pt;margin:18pt 0 8pt}h3{font-size:14pt;margin:16pt 0 6pt}.meta{color:#707782;font-size:9pt;margin-bottom:22pt;padding-bottom:10pt;border-bottom:1px solid #dfe3e9}.note-callout{border-left:3px solid #6179d1;background:#eef2ff;padding:10pt 12pt;margin:12pt 0}.note-callout span{color:#6179d1;font-size:9pt}.note-image{text-align:center;margin:16pt 0}.note-image img{max-width:100%;height:auto}table{width:100%;border-collapse:collapse;margin:12pt 0}th,td{border:1px solid #aeb5c0;padding:6pt}th{background:#eef1f5}blockquote{border-left:3px solid #aab7e8;padding-left:10pt;color:#555e6c}</style></head><body><h1>${esc(lesson)}</h1><div class="meta">课程：${esc(course)}　·　导出日期：${esc(dateText)}</div>${copy.innerHTML}</body></html>`;
  const useDocx=Boolean(window.htmlDocx?.asBlob),blob=useDocx?window.htmlDocx.asBlob(html,{orientation:'portrait'}):new Blob(['\ufeff',html],{type:'application/msword;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');
  link.href=url;link.download=`${safeFilename(course)}-${safeFilename(lesson)}-笔记.${useDocx?'docx':'doc'}`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Word 笔记已下载');
}
$('#saveNote').onclick=()=>{updateCount();saveTranscript();toast('当前课时已保存在网页中')};
$('#downloadWord').onclick=downloadWord;
$('#insertTimestamp').onclick=()=>insertHtml(`<p><span style="color:#6179d1;font:600 12px Inter">${formatTime(state.seconds)}</span>　</p>`);
$$('.format-toolbar button').forEach(btn=>{btn.addEventListener('pointerdown',e=>{captureEditorRange();e.preventDefault()});btn.addEventListener('mousedown',e=>e.preventDefault())});
$$('[data-command]').forEach(btn=>btn.onclick=()=>{restoreEditorRange();document.execCommand(btn.dataset.command,false);btn.classList.toggle('active');captureEditorRange();updateCount()});
function applyBlockFormat(tag){restoreEditorRange();document.execCommand('formatBlock',false,`<${tag}>`);let block=activeBlock();if(block&&block!==editor&&block.tagName.toLowerCase()!==tag&&!['li','td','th'].includes(block.tagName.toLowerCase())){const replacement=document.createElement(tag);[...block.attributes].forEach(attr=>replacement.setAttribute(attr.name,attr.value));replacement.innerHTML=block.innerHTML;block.replaceWith(replacement);const range=document.createRange();range.selectNodeContents(replacement);range.collapse(false);getSelection().removeAllRanges();getSelection().addRange(range)}captureEditorRange();syncFormatToolbar();renderNoteOutline();updateCount()}
$('#blockFormat').onchange=e=>applyBlockFormat(e.target.value);
function selectSizedContent(node){const range=document.createRange();range.selectNodeContents(node);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);savedEditorRange=range.cloneRange()}
function clearNestedFontSizes(root){root.querySelectorAll('[data-note-size],font[size]').forEach(node=>{node.style.removeProperty('font-size');node.removeAttribute('data-note-size');node.removeAttribute('size')})}
function changeFontSize(delta){
  restoreEditorRange();const selection=getSelection(),range=selection.rangeCount?selection.getRangeAt(0):null;
  if(!range||range.collapsed){toast('请先选择要调整字号的文字');return}
  const startElement=range.startContainer.nodeType===Node.ELEMENT_NODE?range.startContainer:range.startContainer.parentElement,base=parseFloat(getComputedStyle(startElement||editor).fontSize)||16,target=Math.max(10,Math.min(64,Math.round(base)+delta));
  document.execCommand('styleWithCSS',false,false);document.execCommand('fontSize',false,'7');
  const generated=[...editor.querySelectorAll('font[size="7"]')];
  generated.forEach(node=>{clearNestedFontSizes(node);node.removeAttribute('size');node.style.setProperty('font-size',`${target}px`);node.dataset.noteSize=String(target)});
  captureEditorRange();$('#fontSizeValue').textContent=target;updateCount()
}
$('#fontDecrease').onclick=()=>changeFontSize(-1);$('#fontIncrease').onclick=()=>changeFontSize(1);
$('#textColor').oninput=e=>{restoreEditorRange();document.execCommand('foreColor',false,e.target.value);captureEditorRange();updateCount()};
$('#bulletList').onclick=()=>{restoreEditorRange();document.execCommand('insertUnorderedList',false);captureEditorRange();updateCount()};
function bindTables(){editor.querySelectorAll('table').forEach(table=>{let wrapper=table.closest('.note-table-wrap');if(!wrapper){wrapper=document.createElement('div');wrapper.className='note-table-wrap';wrapper.contentEditable='false';table.before(wrapper);wrapper.appendChild(table)}table.contentEditable='true';if(!wrapper._tableBound){wrapper._tableBound=true;wrapper.addEventListener('pointerup',()=>{setTimeout(updateCount,0)})}})}
function closeTableDialog(){$('#tableDialog').classList.remove('open');$('#tableDialog').setAttribute('aria-hidden','true')}
$('#insertTable').onclick=()=>{captureEditorRange();$('#tableDialog').classList.add('open');$('#tableDialog').setAttribute('aria-hidden','false');$('#tableRows').focus()};
$('#closeTable').onclick=closeTableDialog;$('#cancelTable').onclick=closeTableDialog;
$('#tableForm').onsubmit=e=>{e.preventDefault();const rows=Math.max(1,Math.min(20,Number($('#tableRows').value)||1)),cols=Math.max(1,Math.min(12,Number($('#tableCols').value)||1)),header=$('#tableHeader').checked;let html='<div class="note-table-wrap" contenteditable="false"><table contenteditable="true">';for(let row=0;row<rows;row++){const cell=header&&row===0?'th':'td';html+='<tr>'+Array.from({length:cols},()=>`<${cell}>${cell==='th'?'标题':'内容'}</${cell}>`).join('')+'</tr>'}html+='</table></div><p><br></p>';closeTableDialog();insertHtml(html);bindTables();toast(`已插入 ${rows} 行 × ${cols} 列表格，可拖动右下角调整大小`)};

let cropTarget=null,cropRect=null,cropDrag=null,ocrTarget=null,ocrDrawing=false,ocrWorker=null,ocrDrawRect=null;
function compressImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1800,scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.9))};img.src=reader.result};reader.readAsDataURL(file)})}
async function addImages(files){for(const file of [...files].filter(f=>f.type.startsWith('image/'))){try{const src=await compressImage(file);const fig=document.createElement('figure');fig.className='note-image';fig.contentEditable='false';fig.innerHTML=`<img alt="课堂笔记图片"><div class="image-tools"><button class="crop-image-btn" type="button">自由裁剪</button><button class="ocr-image-btn" type="button">扫描文字</button></div>`;fig.querySelector('img').src=src;editor.appendChild(fig);editor.appendChild(document.createElement('p')).innerHTML='<br>';bindImage(fig)}catch(e){toast('这张图片暂时无法读取')}}updateCount()}
function bindImage(fig){if(!fig.querySelector('.image-tools')){fig.querySelector('.crop-image-btn')?.remove();const tools=document.createElement('div');tools.className='image-tools';tools.innerHTML='<button class="crop-image-btn" type="button">自由裁剪</button><button class="ocr-image-btn" type="button">扫描文字</button>';fig.appendChild(tools)}fig.querySelector('.crop-image-btn')?.addEventListener('click',()=>openCrop(fig));fig.querySelector('.ocr-image-btn')?.addEventListener('click',()=>openOcr(fig))}
function containedRect(stage,img){const sw=stage.clientWidth,sh=stage.clientHeight,ir=img.naturalWidth/img.naturalHeight,sr=sw/sh;let w,h,x,y;if(ir>sr){w=sw;h=w/ir;x=0;y=(sh-h)/2}else{h=sh;w=h*ir;y=0;x=(sw-w)/2}return{x,y,w,h}}
function renderCrop(){if(!cropRect)return;const box=$('#cropBox');box.style.left=`${cropRect.x}px`;box.style.top=`${cropRect.y}px`;box.style.width=`${cropRect.w}px`;box.style.height=`${cropRect.h}px`}
function openCrop(fig){cropTarget=fig;const preview=$('#cropImage');preview.onload=()=>{const r=containedRect($('#cropPreview'),preview);cropRect={x:r.x+r.w*.08,y:r.y+r.h*.08,w:r.w*.84,h:r.h*.84};renderCrop()};preview.src=fig.querySelector('img').src;$('#cropDialog').classList.add('open');$('#cropDialog').setAttribute('aria-hidden','false')}
function closeCrop(){$('#cropDialog').classList.remove('open');$('#cropDialog').setAttribute('aria-hidden','true');cropTarget=null;cropDrag=null}
$('#closeCrop').onclick=closeCrop;$('#cancelCrop').onclick=closeCrop;
$('#cropBox').addEventListener('pointerdown',e=>{e.preventDefault();const box=e.currentTarget;box.setPointerCapture(e.pointerId);cropDrag={mode:e.target.dataset.handle||'move',startX:e.clientX,startY:e.clientY,start:{...cropRect}}});
$('#cropBox').addEventListener('pointermove',e=>{if(!cropDrag||!cropTarget)return;const bounds=containedRect($('#cropPreview'),$('#cropImage')),dx=e.clientX-cropDrag.startX,dy=e.clientY-cropDrag.startY,s=cropDrag.start,min=44;let r={...s};if(cropDrag.mode==='move'){r.x=Math.max(bounds.x,Math.min(bounds.x+bounds.w-s.w,s.x+dx));r.y=Math.max(bounds.y,Math.min(bounds.y+bounds.h-s.h,s.y+dy))}else{if(cropDrag.mode.includes('e'))r.w=Math.max(min,Math.min(bounds.x+bounds.w-s.x,s.w+dx));if(cropDrag.mode.includes('s'))r.h=Math.max(min,Math.min(bounds.y+bounds.h-s.y,s.h+dy));if(cropDrag.mode.includes('w')){r.x=Math.max(bounds.x,Math.min(s.x+s.w-min,s.x+dx));r.w=s.w+(s.x-r.x)}if(cropDrag.mode.includes('n')){r.y=Math.max(bounds.y,Math.min(s.y+s.h-min,s.y+dy));r.h=s.h+(s.y-r.y)}}cropRect=r;renderCrop()});
$('#cropBox').addEventListener('pointerup',()=>cropDrag=null);$('#cropBox').addEventListener('pointercancel',()=>cropDrag=null);
$('#applyCrop').onclick=()=>{if(!cropTarget||!cropRect)return;const preview=$('#cropImage'),bounds=containedRect($('#cropPreview'),preview),sx=(cropRect.x-bounds.x)*preview.naturalWidth/bounds.w,sy=(cropRect.y-bounds.y)*preview.naturalHeight/bounds.h,sw=cropRect.w*preview.naturalWidth/bounds.w,sh=cropRect.h*preview.naturalHeight/bounds.h,canvas=document.createElement('canvas'),max=1600,scale=Math.min(1,max/Math.max(sw,sh));canvas.width=Math.max(1,Math.round(sw*scale));canvas.height=Math.max(1,Math.round(sh*scale));canvas.getContext('2d').drawImage(preview,sx,sy,sw,sh,0,0,canvas.width,canvas.height);const img=cropTarget.querySelector('img');img.src=canvas.toDataURL('image/jpeg',.9);img.style.transform='';img.style.objectPosition='50% 50%';cropTarget.style.height=`${Math.max(140,Math.min(520,cropTarget.clientWidth/(canvas.width/canvas.height)))}px`;closeCrop();updateCount();toast('已按自由选框完成裁剪')};

function closeOcr(){$('#ocrDialog').classList.remove('open');$('#ocrDialog').setAttribute('aria-hidden','true');ocrTarget=null;ocrDrawing=false}
function openOcr(fig){ocrTarget=fig;$('#ocrResult').value='';$('#copyOcr').disabled=true;$('#insertOcr').disabled=true;$('#ocrProgress').textContent='请涂抹需要扫描的区域';$('#ocrDialog').classList.add('open');$('#ocrDialog').setAttribute('aria-hidden','false');const img=new Image();img.onload=()=>prepareOcrCanvas(img);img.src=fig.querySelector('img').src}
function prepareOcrCanvas(img){const stage=$('#ocrStage'),base=$('#ocrImageCanvas'),mask=$('#ocrMaskCanvas'),w=Math.round(stage.clientWidth),h=Math.round(stage.clientHeight);base.width=mask.width=w;base.height=mask.height=h;const ctx=base.getContext('2d');ctx.clearRect(0,0,w,h);const ir=img.naturalWidth/img.naturalHeight,sr=w/h;let dw,dh,dx,dy;if(ir>sr){dw=w;dh=w/ir;dx=0;dy=(h-dh)/2}else{dh=h;dw=h*ir;dy=0;dx=(w-dw)/2}ctx.drawImage(img,dx,dy,dw,dh);ocrDrawRect={x:dx,y:dy,w:dw,h:dh};mask.getContext('2d').clearRect(0,0,w,h)}
function maskPoint(e){const rect=$('#ocrMaskCanvas').getBoundingClientRect();return{x:(e.clientX-rect.left)*$('#ocrMaskCanvas').width/rect.width,y:(e.clientY-rect.top)*$('#ocrMaskCanvas').height/rect.height}}
function drawMask(e){if(!ocrDrawing)return;const canvas=$('#ocrMaskCanvas'),ctx=canvas.getContext('2d'),p=maskPoint(e),size=Number($('#brushSize').value);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=size;ctx.strokeStyle='rgba(95,127,245,.58)';ctx.lineTo(p.x,p.y);ctx.stroke();ctx.beginPath();ctx.moveTo(p.x,p.y);$('#ocrProgress').textContent='已选择区域，可以开始识别'}
$('#ocrMaskCanvas').addEventListener('pointerdown',e=>{e.preventDefault();ocrDrawing=true;e.currentTarget.setPointerCapture(e.pointerId);const p=maskPoint(e),ctx=e.currentTarget.getContext('2d');ctx.beginPath();ctx.moveTo(p.x,p.y);drawMask(e)});$('#ocrMaskCanvas').addEventListener('pointermove',drawMask);$('#ocrMaskCanvas').addEventListener('pointerup',()=>ocrDrawing=false);$('#ocrMaskCanvas').addEventListener('pointercancel',()=>ocrDrawing=false);
$('#clearMask').onclick=()=>{const c=$('#ocrMaskCanvas');c.getContext('2d').clearRect(0,0,c.width,c.height);$('#ocrProgress').textContent='已清除，请重新涂抹'};
function selectedOcrImage(){const base=$('#ocrImageCanvas'),mask=$('#ocrMaskCanvas'),mctx=mask.getContext('2d'),m=mctx.getImageData(0,0,mask.width,mask.height),bctx=base.getContext('2d'),b=bctx.getImageData(0,0,base.width,base.height);let minX=mask.width,minY=mask.height,maxX=-1,maxY=-1;for(let y=0;y<mask.height;y++)for(let x=0;x<mask.width;x++){if(m.data[(y*mask.width+x)*4+3]>20){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}}if(maxX<0)return null;minX=Math.max(0,minX-8);minY=Math.max(0,minY-8);maxX=Math.min(mask.width-1,maxX+8);maxY=Math.min(mask.height-1,maxY+8);const out=document.createElement('canvas');out.width=maxX-minX+1;out.height=maxY-minY+1;const octx=out.getContext('2d'),odata=octx.createImageData(out.width,out.height);for(let y=0;y<out.height;y++)for(let x=0;x<out.width;x++){const si=((minY+y)*mask.width+minX+x)*4,di=(y*out.width+x)*4,selected=m.data[si+3]>20;odata.data[di]=selected?b.data[si]:255;odata.data[di+1]=selected?b.data[si+1]:255;odata.data[di+2]=selected?b.data[si+2]:255;odata.data[di+3]=255}octx.putImageData(odata,0,0);return out}
function loadTesseract(){if(window.Tesseract)return Promise.resolve();return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';script.onload=resolve;script.onerror=reject;document.head.appendChild(script)})}
$('#scanText').onclick=async()=>{const selected=selectedOcrImage();if(!selected){toast('请先涂抹需要扫描的文字区域');return}const btn=$('#scanText');btn.disabled=true;try{$('#ocrProgress').textContent='正在载入文字识别…';await loadTesseract();if(!ocrWorker)ocrWorker=await Tesseract.createWorker('chi_sim+eng',1,{logger:m=>{if(m.progress)$('#ocrProgress').textContent=`正在识别 ${Math.round(m.progress*100)}%`}});const result=await ocrWorker.recognize(selected);const text=result.data.text.trim();$('#ocrResult').value=text;$('#copyOcr').disabled=!text;$('#insertOcr').disabled=!text;$('#ocrProgress').textContent=text?'识别完成，可修改后使用':'没有识别到文字，请扩大涂抹区域'}catch(e){$('#ocrProgress').textContent='识别服务加载失败';toast('文字识别暂时不可用，请检查网络后重试')}finally{btn.disabled=false}};
$('#closeOcr').onclick=closeOcr;$('#cancelOcr').onclick=closeOcr;$('#copyOcr').onclick=async()=>{await navigator.clipboard.writeText($('#ocrResult').value);toast('文字已复制')};$('#insertOcr').onclick=()=>{const text=$('#ocrResult').value.trim();if(!text)return;insertHtml(`<blockquote>${text.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c])).replace(/\n/g,'<br>')}</blockquote><p><br></p>`);closeOcr();toast('扫描文字已插入笔记')};
$('#imageButton').onclick=()=>$('#imageInput').click();$('#imageInput').onchange=e=>{addImages(e.target.files);e.target.value=''};
const editorWrap=$('.editor-wrap');['dragenter','dragover'].forEach(type=>editorWrap.addEventListener(type,e=>{e.preventDefault();editorWrap.classList.add('dragging')}));['dragleave','drop'].forEach(type=>editorWrap.addEventListener(type,e=>{e.preventDefault();editorWrap.classList.remove('dragging')}));editorWrap.addEventListener('drop',e=>addImages(e.dataTransfer.files));editor.querySelectorAll('.note-image').forEach(bindImage);

let coursewareDbPromise=null,coursewareUrls=[];
function openCoursewareDb(){if(coursewareDbPromise)return coursewareDbPromise;coursewareDbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open('keji-local-files',1);request.onupgradeneeded=()=>{const db=request.result,store=db.createObjectStore('courseware',{keyPath:'id'});store.createIndex('lessonId','lessonId')};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return coursewareDbPromise}
async function coursewareStore(mode,run){const db=await openCoursewareDb();return new Promise((resolve,reject)=>{const tx=db.transaction('courseware',mode),store=tx.objectStore('courseware'),request=run(store);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
const getCourseware=id=>coursewareStore('readonly',store=>store.get(id));
const getLessonCourseware=async lessonId=>(await coursewareStore('readonly',store=>store.index('lessonId').getAll(IDBKeyRange.only(lessonId)))).sort((a,b)=>b.addedAt-a.addedAt);
const removeCourseware=id=>coursewareStore('readwrite',store=>store.delete(id));
async function removeLessonCourseware(lessonId){try{const items=await getLessonCourseware(lessonId);await Promise.all(items.map(item=>removeCourseware(item.id)))}catch(e){}}
function clearCoursewareUrls(){coursewareUrls.forEach(URL.revokeObjectURL);coursewareUrls=[]}
function fileSize(bytes){return bytes>1024*1024?`${(bytes/1024/1024).toFixed(1)} MB`:`${Math.max(1,Math.round(bytes/1024))} KB`}
function coursewareKind(name){const ext=name.split('.').pop()?.toLowerCase();return ext==='pdf'?'PDF':ext==='pptx'?'PPTX':'PPT'}
async function renderCoursewareList(selectId){const list=$('#coursewareList');try{const items=await getLessonCourseware(state.currentLesson);if(!items.length){list.innerHTML='<div class="dialog-empty"><b>还没有课件</b><span>导入 PPTX、PPT 或 PDF</span></div>';$('#coursewarePreview').innerHTML='<div class="dialog-empty"><b>导入本课课件</b><span>文件只保存在这台设备的当前浏览器。</span></div>';return}list.innerHTML=items.map(item=>`<button class="courseware-item${item.id===selectId?' active':''}" data-file="${item.id}"><span>${coursewareKind(item.name)}</span><span><b>${esc(item.name)}</b><small>${fileSize(item.size)}</small></span><span class="delete-file" data-delete-file="${item.id}" title="删除">×</span></button>`).join('');$$('.courseware-item').forEach(btn=>btn.onclick=e=>{if(e.target.closest('[data-delete-file]'))return;previewCourseware(btn.dataset.file)});$$('[data-delete-file]').forEach(btn=>btn.onclick=async e=>{e.stopPropagation();if(!confirm('删除这个课件？'))return;await removeCourseware(btn.dataset.deleteFile);clearCoursewareUrls();await renderCoursewareList();toast('课件已删除')});if(selectId)previewCourseware(selectId)}catch(e){list.innerHTML='<div class="dialog-empty"><b>无法读取课件</b><span>请检查浏览器是否允许本地存储。</span></div>'}}
function loadJsZip(){if(window.JSZip)return Promise.resolve();return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js';script.onload=resolve;script.onerror=reject;document.head.appendChild(script)})}
function xmlText(xml){const doc=new DOMParser().parseFromString(xml,'application/xml');return [...doc.getElementsByTagNameNS('*','t')].map(node=>node.textContent.trim()).filter(Boolean)}
async function extractPptxSlides(blob){await loadJsZip();const zip=await JSZip.loadAsync(await blob.arrayBuffer()),paths=Object.keys(zip.files).filter(path=>/^ppt\/slides\/slide\d+\.xml$/.test(path)).sort((a,b)=>Number(a.match(/\d+/)[0])-Number(b.match(/\d+/)[0])),slides=[];for(const path of paths){const xml=await zip.file(path).async('string'),texts=xmlText(xml),number=Number(path.match(/slide(\d+)/)[1]),relsPath=`ppt/slides/_rels/slide${number}.xml.rels`,images=[];if(zip.file(relsPath)){const rels=new DOMParser().parseFromString(await zip.file(relsPath).async('string'),'application/xml');for(const relation of [...rels.getElementsByTagName('Relationship')]){const target=relation.getAttribute('Target')||'';if(!/media\//.test(target))continue;const mediaPath=target.startsWith('../media/')?`ppt/media/${target.split('/').pop()}`:target.replace(/^\//,'');const entry=zip.file(mediaPath);if(entry){const url=URL.createObjectURL(await entry.async('blob'));coursewareUrls.push(url);images.push(url)}}}slides.push({number,texts,images})}return slides}
async function previewCourseware(id){const area=$('#coursewarePreview');clearCoursewareUrls();$$('.courseware-item').forEach(btn=>btn.classList.toggle('active',btn.dataset.file===id));area.innerHTML='<div class="dialog-empty"><b>正在打开课件…</b><span>较大的文件可能需要几秒钟。</span></div>';try{const item=await getCourseware(id);if(!item)return;const url=URL.createObjectURL(item.blob);coursewareUrls.push(url);const head=`<div class="preview-head"><div><b>${esc(item.name)}</b><span>${fileSize(item.size)} · ${new Date(item.addedAt).toLocaleDateString('zh-CN')}</span></div><a href="${url}" download="${esc(item.name)}">下载原文件</a></div>`;if(coursewareKind(item.name)==='PDF'){area.innerHTML=`${head}<iframe src="${url}" title="${esc(item.name)}"></iframe>`;return}if(coursewareKind(item.name)==='PPT'){area.innerHTML=`${head}<div class="dialog-empty"><b>旧版 .ppt 暂不能直接预览</b><span>可以下载原文件查看，或另存为 .pptx / PDF 后重新导入。</span></div>`;return}const slides=await extractPptxSlides(item.blob);area.innerHTML=`${head}<p class="preview-notice">网页会保留课件文字和图片，复杂排版、公式与动画可能无法完全还原。</p><div class="ppt-slides">${slides.map(slide=>`<article class="ppt-slide">${slide.texts.length?`<h3>${esc(slide.texts[0])}</h3>${slide.texts.length>1?`<ul>${slide.texts.slice(1).map(text=>`<li>${esc(text)}</li>`).join('')}</ul>`:''}`:'<p>此页没有可提取的文字。</p>'}${slide.images.length?`<div class="ppt-images">${slide.images.map(src=>`<img src="${src}" alt="第 ${slide.number} 页图片">`).join('')}</div>`:''}<em>${slide.number} / ${slides.length}</em></article>`).join('')}</div>`}catch(e){area.innerHTML='<div class="dialog-empty"><b>课件预览失败</b><span>文件可能已损坏，仍可从左侧重新选择或删除。</span></div>'}}
async function addCoursewareFiles(files){for(const file of [...files]){if(!/\.(ppt|pptx|pdf)$/i.test(file.name)){toast('仅支持 PPT、PPTX 和 PDF');continue}try{const item={id:uid('file'),lessonId:state.currentLesson,name:file.name,type:file.type,size:file.size,addedAt:Date.now(),blob:file};await coursewareStore('readwrite',store=>store.put(item));await renderCoursewareList(item.id);toast('课件已导入当前课时')}catch(e){toast('课件保存失败，可能是浏览器空间不足')}}}
function openCourseware(){clearCoursewareUrls();$('#coursewareDialog').classList.add('open');$('#coursewareDialog').setAttribute('aria-hidden','false');$('#coursewareLessonName').textContent=`${currentCourse()?.name||''} · ${currentLesson()?.name||''}`;renderCoursewareList()}
function closeCourseware(){clearCoursewareUrls();$('#coursewareDialog').classList.remove('open');$('#coursewareDialog').setAttribute('aria-hidden','true')}
$('#coursewareButton').onclick=openCourseware;$('#closeCourseware').onclick=closeCourseware;$('#addCourseware').onclick=()=>$('#coursewareInput').click();$('#coursewareInput').onchange=e=>{addCoursewareFiles(e.target.files);e.target.value=''};
function setRecordingUI(on){state.recording=on;recordBtn.classList.toggle('recording',on);recordBtn.querySelector('#recordLabel').textContent=on?'录音中':'开始录音';pauseBtn.disabled=!on;stopBtn.disabled=!on;$('#lostBtn').disabled=!on;$('#recordingMotion').classList.toggle('active',on&&!state.paused);$('#liveState').classList.toggle('on',on&&!state.paused);$('#liveState span').textContent=on?(state.paused?'已暂停':'正在转写'):'录音已结束';if(on){audio.pause();seek.disabled=true;pauseBtn.textContent='Ⅱ'}}
async function startRecording(){
  try{
    state.stream=await navigator.mediaDevices.getUserMedia({audio:true});state.chunks=[];
    state.mediaRecorder=new MediaRecorder(state.stream);state.mediaRecorder.ondataavailable=e=>{if(e.data.size)state.chunks.push(e.data)};
    state.mediaRecorder.onstop=()=>{const blob=new Blob(state.chunks,{type:state.mediaRecorder.mimeType});state.recordedDuration=state.seconds;if(state.playbackUrl)URL.revokeObjectURL(state.playbackUrl);state.playbackUrl=URL.createObjectURL(blob);audio.src=state.playbackUrl;audio.load();seek.value=0;seek.disabled=false;pauseBtn.disabled=false;pauseBtn.textContent='▶';timerEl.textContent='00:00:00';$('#totalTime').textContent=formatTime(state.recordedDuration);localStorage.setItem('keji-last-duration',String(state.recordedDuration));toast('录音已就绪，可以拖动进度条回听')};
    state.mediaRecorder.start();state.seconds=0;timerEl.textContent='00:00:00';$('#totalTime').textContent='00:00:00';seek.value=0;state.paused=false;setRecordingUI(true);
    state.timer=setInterval(()=>{state.seconds++;timerEl.textContent=formatTime(state.seconds)},1000);startRecognition();toast('录音已开始');
  }catch(e){toast('未获得麦克风权限，请在浏览器地址栏允许录音')}
}
function stopRecording(){if(!state.recording)return;clearInterval(state.timer);if(state.mediaRecorder&&state.mediaRecorder.state!=='inactive')state.mediaRecorder.stop();state.stream?.getTracks().forEach(t=>t.stop());state.recognition?.stop();setRecordingUI(false);state.paused=false;pauseBtn.disabled=true;$('#recordingMotion').classList.remove('active');$('#durationMeta').textContent=`录音 ${formatTime(state.seconds)}`}
function togglePause(){if(!state.recording)return;state.paused=!state.paused;if(state.paused){state.mediaRecorder?.pause();clearInterval(state.timer);state.recognition?.stop()}else{state.mediaRecorder?.resume();state.timer=setInterval(()=>{state.seconds++;timerEl.textContent=formatTime(state.seconds)},1000);startRecognition()}pauseBtn.textContent=state.paused?'▶':'Ⅱ';$('#recordingMotion').classList.toggle('active',!state.paused);$('#liveState span').textContent=state.paused?'已暂停':'正在转写'}
function togglePlayback(){if(!audio.src)return;if(audio.paused){audio.play();pauseBtn.textContent='Ⅱ'}else{audio.pause();pauseBtn.textContent='▶'}}
recordBtn.onclick=()=>state.recording?togglePause():startRecording();pauseBtn.onclick=()=>state.recording?togglePause():togglePlayback();stopBtn.onclick=stopRecording;
audio.addEventListener('timeupdate',()=>{const duration=Number.isFinite(audio.duration)?audio.duration:state.recordedDuration;if(!duration)return;seek.value=String(audio.currentTime/duration*100);timerEl.textContent=formatTime(Math.floor(audio.currentTime));$('#totalTime').textContent=formatTime(Math.floor(duration))});
audio.addEventListener('ended',()=>{pauseBtn.textContent='▶';seek.value=0;timerEl.textContent='00:00:00'});
audio.addEventListener('pause',()=>{if(!state.recording)pauseBtn.textContent='▶'});
seek.addEventListener('input',()=>{const duration=Number.isFinite(audio.duration)?audio.duration:state.recordedDuration;if(duration){audio.currentTime=duration*Number(seek.value)/100;timerEl.textContent=formatTime(Math.floor(audio.currentTime))}});
function smartCorrect(text){return text.replace(/\s+/g,'').replace(/^(嗯|呃|啊)[，,、\s]*/,'').replace(/(然后就是说|就是说|然后呢|这个这个|那个那个)/g,m=>m==='然后就是说'?'随后，':'').replace(/([呢啊吧嘛])\1+/g,'$1').replace(/，{2,}/g,'，').replace(/([。！？]){2,}/g,'$1').replace(/([^。！？])$/,'$1。')}
function displayTranscript(block){const showCorrected=$('#autoCorrect').checked&&!block.classList.contains('muted');const p=block.querySelector('p');p.textContent=showCorrected?smartCorrect(block.dataset.raw||p.textContent):(block.dataset.raw||p.textContent);block.classList.toggle('corrected',showCorrected);p.title=showCorrected?`原始转写：${block.dataset.raw||''}`:''}
$('#autoCorrect').onchange=e=>{$$('.transcript-block:not(#transcriptHint)').forEach(displayTranscript);localStorage.setItem('keji-auto-correct',String(e.target.checked));toast(e.target.checked?'已开启自动校正，原始转写仍会保留':'已显示原始转写')};
$('#autoCorrect').checked=localStorage.getItem('keji-auto-correct')==='true';
function startRecognition(){const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition)return;try{const r=new SpeechRecognition();r.lang='zh-CN';r.continuous=true;r.interimResults=true;let interim=null;r.onresult=e=>{let finalText='',temp='';for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)finalText+=e.results[i][0].transcript;else temp+=e.results[i][0].transcript}if(temp){if(!interim){interim=addTranscript(temp,true)}else{interim.dataset.raw=temp;displayTranscript(interim)}}if(finalText){if(interim){interim.dataset.raw=finalText;interim.classList.remove('muted');displayTranscript(interim);saveTranscript();interim=null}else addTranscript(finalText,false)}};r.onend=()=>{if(state.recording&&!state.paused)setTimeout(startRecognition,350)};r.start();state.recognition=r}catch(e){}}
function addTranscript(text,muted=false){$('#transcriptHint')?.remove();const wrap=document.createElement('div');wrap.className=`transcript-block${muted?' muted':''}`;wrap.dataset.time=formatTime(state.seconds);wrap.dataset.raw=text;wrap.innerHTML=`<button>${formatTime(state.seconds)}</button><p></p><button class="quote-btn" title="添加到笔记">＋</button>`;displayTranscript(wrap);$('#transcriptList').appendChild(wrap);bindTranscript(wrap);$('#transcriptList').scrollTop=$('#transcriptList').scrollHeight;if(!muted)saveTranscript();return wrap}
function bindTranscript(block){block.querySelector('.quote-btn')?.addEventListener('click',()=>{insertHtml(`<div class="note-callout"><span>${block.dataset.time}</span><p>${block.querySelector('p').textContent}</p></div>`);toast('已添加到你的笔记')});block.querySelector('button:first-child')?.addEventListener('click',()=>toast(`已定位到 ${block.dataset.time}`))}
function transcriptItems(){return [...$$('.transcript-block:not(.muted):not(#transcriptHint)')].map(block=>({time:block.dataset.time||'00:00:00',text:block.dataset.raw||block.querySelector('p')?.textContent||''})).filter(x=>x.text.trim())}
function saveTranscript(){try{localStorage.setItem(`keji-transcript-${state.currentLesson}`,JSON.stringify(transcriptItems()))}catch(e){}}
function loadTranscript(lessonId){const saved=JSON.parse(localStorage.getItem(`keji-transcript-${lessonId}`)||'[]'),list=$('#transcriptList');list.innerHTML='';if(!saved.length){list.innerHTML='<div class="transcript-block muted" id="transcriptHint"><button>--:--:--</button><p>开始录音后，新的转写内容会出现在这里。</p></div>';return}saved.forEach(item=>{const block=document.createElement('div');block.className='transcript-block';block.dataset.time=item.time;block.dataset.raw=item.text;block.innerHTML=`<button>${item.time}</button><p></p><button class="quote-btn" title="添加到笔记">＋</button>`;displayTranscript(block);list.appendChild(block);bindTranscript(block)})}
$$('.transcript-block:not(#transcriptHint)').forEach(block=>{block.dataset.raw=block.querySelector('p').textContent;bindTranscript(block);displayTranscript(block)});
$('#lostBtn').onclick=()=>{insertHtml(`<p>🔖 <strong>${formatTime(state.seconds)}</strong>　刚刚走神了，课后回听这一段。</p>`);toast('已标记，课后会优先整理前后两分钟')};
$('#collapseSidebar').onclick=()=>$('#sidebar').classList.toggle('collapsed');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const uid=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;
function saveCourses(){localStorage.setItem('keji-courses',JSON.stringify(state.courses))}
function currentCourse(){return state.courses.find(c=>c.id===state.currentCourse)}
function currentLesson(){return currentCourse()?.lessons.find(l=>l.id===state.currentLesson)}
function firstAvailableLesson(){for(const course of state.courses){if(course.lessons.length)return{course,lesson:course.lessons[0]}}return null}
let plannerCourseId=null;
function getCoursePlan(courseId){try{return JSON.parse(localStorage.getItem(`keji-plan-${courseId}`)||'null')||{todos:[],memo:''}}catch(e){return{todos:[],memo:''}}}
function saveCoursePlan(courseId,plan){localStorage.setItem(`keji-plan-${courseId}`,JSON.stringify(plan))}
function pendingTodoCount(courseId){return getCoursePlan(courseId).todos.filter(todo=>!todo.done).length}
function renderPlanner(){const course=state.courses.find(item=>item.id===plannerCourseId);if(!course)return;const plan=getCoursePlan(plannerCourseId),today=new Date().toISOString().slice(0,10);$('#plannerTitle').textContent=`${course.name} · 待办与备忘`;$('#courseMemo').value=plan.memo||'';$('#todoList').innerHTML=plan.todos.length?plan.todos.slice().sort((a,b)=>Number(a.done)-Number(b.done)||(a.date||'9999').localeCompare(b.date||'9999')).map(todo=>`<div class="todo-item${todo.done?' done':''}${!todo.done&&todo.date&&todo.date<today?' overdue':''}" data-todo="${todo.id}"><input type="checkbox" ${todo.done?'checked':''} aria-label="完成待办"><span><b>${esc(todo.text)}</b><small>${todo.date?`截止 ${esc(todo.date)}`:'未设置截止日期'}</small></span><button title="删除">×</button></div>`).join(''):'<div class="dialog-empty"><b>暂无待办</b><span>把作业要求和 DDL 记在这里。</span></div>';$$('.todo-item input').forEach(input=>input.onchange=()=>{const todoId=input.closest('.todo-item').dataset.todo,item=plan.todos.find(todo=>todo.id===todoId);item.done=input.checked;saveCoursePlan(plannerCourseId,plan);renderPlanner();renderTree()});$$('.todo-item button').forEach(btn=>btn.onclick=()=>{const todoId=btn.closest('.todo-item').dataset.todo;plan.todos=plan.todos.filter(todo=>todo.id!==todoId);saveCoursePlan(plannerCourseId,plan);renderPlanner();renderTree()})}
function openPlanner(courseId){plannerCourseId=courseId;$('#plannerDialog').classList.add('open');$('#plannerDialog').setAttribute('aria-hidden','false');renderPlanner()}
function closePlanner(){$('#plannerDialog').classList.remove('open');$('#plannerDialog').setAttribute('aria-hidden','true');plannerCourseId=null}
$('#closePlanner').onclick=closePlanner;$('#todoForm').onsubmit=e=>{e.preventDefault();const text=$('#todoText').value.trim();if(!text||!plannerCourseId)return;const plan=getCoursePlan(plannerCourseId);plan.todos.push({id:uid('todo'),text,date:$('#todoDate').value,done:false});saveCoursePlan(plannerCourseId,plan);$('#todoText').value='';$('#todoDate').value='';renderPlanner();renderTree();toast('待办已添加')};$('#courseMemo').oninput=e=>{if(!plannerCourseId)return;const plan=getCoursePlan(plannerCourseId);plan.memo=e.target.value;saveCoursePlan(plannerCourseId,plan)};
$('#coursePlannerButton').onclick=()=>openPlanner(state.currentCourse);
function renderTree(){const tree=$('#courseTree');tree.innerHTML=state.courses.map(course=>{const pending=pendingTodoCount(course.id);return`<div class="course-group" data-course-group="${course.id}"><div class="course-row"><button class="course ${course.id===state.currentCourse?'active':''}" data-course="${course.id}" aria-expanded="${course.open}"><span class="folder-icon">▰</span><span class="course-label">${esc(course.name)}${pending?`<em class="course-badge">${pending}</em>`:''}</span><span class="chevron">${course.open?'⌄':'›'}</span></button><div class="course-tools"><button class="tree-action course-plan" data-course="${course.id}" title="待办与备忘">☑</button><button class="tree-action add-lesson" data-course="${course.id}" title="添加课时">＋</button><button class="tree-action rename-course" data-course="${course.id}" title="重命名课程">✎</button><button class="tree-action danger delete-course" data-course="${course.id}" title="删除课程">×</button></div></div><div class="lesson-list ${course.open?'open':''}">${course.lessons.length?course.lessons.map((lesson,i)=>`<div class="lesson-row ${lesson.id===state.currentLesson?'active':''}"><button class="lesson" data-course="${course.id}" data-lesson="${lesson.id}" title="双击可重命名"><span>${pad(i+1)}</span><b>${esc(lesson.name)}</b></button><button class="tree-action danger lesson-delete" data-course="${course.id}" data-lesson="${lesson.id}" title="删除课时">×</button></div>`).join(''):`<div class="empty-course">暂无课时，点击 ＋ 添加</div>`}</div></div>`}).join('');bindTree()}
function bindTree(){
  $$('.course').forEach(btn=>btn.onclick=()=>{const course=state.courses.find(c=>c.id===btn.dataset.course);course.open=!course.open;state.currentCourse=course.id;saveCourses();renderTree()});
  $$('.lesson').forEach(btn=>{btn.onclick=e=>{e.stopPropagation();switchLesson(btn.dataset.course,btn.dataset.lesson)};btn.ondblclick=e=>{e.stopPropagation();renameLesson(btn.dataset.course,btn.dataset.lesson)}});
  $$('.course-plan').forEach(btn=>btn.onclick=e=>{e.stopPropagation();openPlanner(btn.dataset.course)});
  $$('.add-lesson').forEach(btn=>btn.onclick=e=>{e.stopPropagation();addLesson(btn.dataset.course)});
  $$('.rename-course').forEach(btn=>btn.onclick=e=>{e.stopPropagation();renameCourse(btn.dataset.course)});
  $$('.delete-course').forEach(btn=>btn.onclick=e=>{e.stopPropagation();deleteCourse(btn.dataset.course)});
  $$('.lesson-delete').forEach(btn=>btn.onclick=e=>{e.stopPropagation();deleteLesson(btn.dataset.course,btn.dataset.lesson)});
}
function switchLesson(courseId,lessonId){if(state.recording){toast('请先结束当前录音，再切换课时');return}updateCount();saveTranscript();audio.pause();const course=state.courses.find(c=>c.id===courseId),lesson=course?.lessons.find(l=>l.id===lessonId);if(!lesson)return;state.currentCourse=courseId;state.currentLesson=lessonId;course.open=true;$('#courseName').textContent=course.name;$('#lessonTitle').textContent=lesson.name;editor.innerHTML=localStorage.getItem(`keji-notes-${lessonId}`)||'<p><br></p>';savedEditorRange=null;editor.querySelectorAll('.note-image').forEach(bindImage);bindTables();renderNoteOutline();loadTranscript(lessonId);saveCourses();renderTree();updateCount()}
function addLesson(courseId){const name=prompt('新课时名称');if(!name?.trim())return;const course=state.courses.find(c=>c.id===courseId),lesson={id:uid('lesson'),name:name.trim()};course.lessons.push(lesson);course.open=true;saveCourses();switchLesson(courseId,lesson.id);toast('课时已创建')}
function renameCourse(courseId){const course=state.courses.find(c=>c.id===courseId),name=prompt('修改课程名称',course.name);if(!name?.trim())return;course.name=name.trim();if(course.id===state.currentCourse)$('#courseName').textContent=course.name;saveCourses();renderTree()}
function renameLesson(courseId,lessonId){const course=state.courses.find(c=>c.id===courseId),lesson=course.lessons.find(l=>l.id===lessonId),name=prompt('修改课时名称',lesson.name);if(!name?.trim())return;lesson.name=name.trim();if(lesson.id===state.currentLesson)$('#lessonTitle').textContent=lesson.name;saveCourses();renderTree()}
function deleteCourse(courseId){const course=state.courses.find(c=>c.id===courseId);if(!confirm(`删除课程“${course.name}”及其全部课时？此操作无法撤销。`))return;course.lessons.forEach(l=>{localStorage.removeItem(`keji-notes-${l.id}`);localStorage.removeItem(`keji-transcript-${l.id}`);removeLessonCourseware(l.id)});localStorage.removeItem(`keji-plan-${courseId}`);state.courses=state.courses.filter(c=>c.id!==courseId);ensureSelection();editor.querySelectorAll('.note-image').forEach(bindImage);bindTables();renderNoteOutline();loadTranscript(state.currentLesson);saveCourses();renderTree();toast('课程已删除')}
function deleteLesson(courseId,lessonId){const course=state.courses.find(c=>c.id===courseId),lesson=course.lessons.find(l=>l.id===lessonId);if(!confirm(`删除课时“${lesson.name}”？`))return;course.lessons=course.lessons.filter(l=>l.id!==lessonId);localStorage.removeItem(`keji-notes-${lessonId}`);localStorage.removeItem(`keji-transcript-${lessonId}`);removeLessonCourseware(lessonId);ensureSelection();editor.querySelectorAll('.note-image').forEach(bindImage);bindTables();renderNoteOutline();loadTranscript(state.currentLesson);saveCourses();renderTree();toast('课时已删除')}
function ensureSelection(){let course=state.courses.find(c=>c.id===state.currentCourse),lesson=course?.lessons.find(l=>l.id===state.currentLesson);if(!lesson){let next=firstAvailableLesson();if(!next){course={id:uid('course'),name:'未命名课程',open:true,lessons:[{id:uid('lesson'),name:'第1节课'}]};state.courses.push(course);next={course,lesson:course.lessons[0]}}course=next.course;lesson=next.lesson;state.currentCourse=course.id;state.currentLesson=lesson.id}$('#courseName').textContent=course.name;$('#lessonTitle').textContent=lesson.name;editor.innerHTML=localStorage.getItem(`keji-notes-${lesson.id}`)||'<p><br></p>';savedEditorRange=null}
function splitSentences(text){return [...new Set(String(text||'').replace(/\r/g,'\n').split(/(?:[。！？!?；;]\s*|\n+)/).map(x=>x.replace(/\s+/g,' ').trim()).filter(x=>x.length>3&&x!=='自由裁剪'&&x!=='扫描文字'))]}
function trimText(text,max=46){const value=String(text||'').trim();return value.length>max?`${value.slice(0,max)}…`:value}
function collectStudyData(){
  const title=$('#lessonTitle').textContent.trim();
  const noteClone=editor.cloneNode(true);noteClone.querySelectorAll('.image-tools,button').forEach(node=>node.remove());
  const notes=splitSentences(noteClone.innerText).filter(text=>text!==title);
  const transcript=transcriptItems().map(item=>({...item,text:item.text.replace(/\s+/g,'').trim()})).filter(item=>item.text.length>3);
  return{title,notes,transcript,all:[...notes,...transcript.map(item=>item.text)]};
}
function emptyGenerated(container,message){container.innerHTML=`<div class="generate-empty"><span>⌘</span><h3>内容还不够</h3><p>${esc(message)}</p></div>`}
function keywordScore(text){return/(重点|重要|注意|考试|考点|必须|记住|核心|关键|所以|因此|区别|结论)/.test(text)}
function findEmphasis(data){return data.transcript.find(item=>keywordScore(item.text))||data.transcript[0]||null}
function pointKind(text){
  if(/(是指|指的是|定义|概念|所谓|即为|称为|包括|分为)/.test(text))return'核心概念';
  if(/(因为|由于|导致|影响|作用|机制|因此|所以|从而|关系|相关)/.test(text))return'机制与联系';
  if(/(区别|不同|相同|相比|比较|而是|但是|然而|优点|缺点)/.test(text))return'比较与辨析';
  if(/(首先|其次|然后|最后|步骤|阶段|过程|方法|如何|条件)/.test(text))return'方法与过程';
  if(/(例如|比如|实验|研究发现|数据显示|案例|表现为|证明)/.test(text))return'例子与证据';
  if(/(应用|实践|用于|意义|启示|干预|治疗|结论|注意|重点|考试|考点|记住)/.test(text))return'结论与应用';
  return'核心要点';
}
function pointScore(text,index){let score=1;if(text.length>=8&&text.length<=90)score+=2;if(keywordScore(text))score+=4;if(/(是指|定义|包括|分为|因为|导致|区别|步骤|结论|研究发现)/.test(text))score+=3;if(/[：:]/.test(text))score+=1;return{score,index}}
function extractMapSections(data){
  const sections=[];let primary=null,secondary=null;
  const blockSelector='h2,h3,p,li,blockquote,tr';
  const blocks=[...editor.querySelectorAll(blockSelector)].filter(node=>{if(node.matches('h2,h3'))return true;if(node.querySelector('h2,h3'))return false;let parent=node.parentElement;while(parent&&parent!==editor){if(parent.matches(blockSelector))return false;parent=parent.parentElement}return true});
  blocks.forEach(node=>{const tag=node.tagName,text=node.innerText?.replace(/\s+/g,' ').trim()||'';if(!text||node.closest('.note-image')||text===data.title)return;
    if(tag==='H2'){primary={label:trimText(text,42),items:[],children:[]};sections.push(primary);secondary=null;return}
    if(tag==='H3'){if(!primary){primary={label:'未归入一级标题',items:[],children:[]};sections.push(primary)}secondary={label:trimText(text,48),items:[]};primary.children.push(secondary);return}
    if(!primary)return;splitSentences(text).map(item=>item.replace(/\s+/g,' ').trim()).filter(item=>item.length>2).slice(0,4).forEach(item=>{const target=secondary?secondary.items:primary.items;if(!target.includes(item))target.push(trimText(item,80))})
  });
  return sections.map(section=>({...section,items:section.items.slice(0,5),children:section.children.map(child=>({...child,items:child.items.slice(0,5)}))})).slice(0,10);
}
function generateMindmap(showToast=true){
  updateCount();const data=collectStudyData(),canvas=$('#mapCanvas');
  if(data.notes.join('').length<4){emptyGenerated(canvas,'先在“我的笔记”中随手记下一些课堂内容，再回来生成思维导图。');if(showToast)toast('先添加一些笔记内容');return}
  const groups=extractMapSections(data);if(!groups.length){emptyGenerated(canvas,'请先在笔记中设置一级标题或二级标题，再生成思维导图。');return}
  canvas.innerHTML=`<div class="map-tree"><div class="map-root-card"><span>本节课</span><strong>${esc(trimText(data.title,30))}</strong><small>${groups.length} 个一级分支</small></div><div class="map-branches">${groups.map((group,index)=>`<section class="map-branch-card"><div class="map-branch-title"><span>${pad(index+1)}</span><b>${esc(group.label)}</b></div><div class="map-subbranches">${group.items.length?`<div class="map-primary-notes">${group.items.map(item=>`<div class="map-detail">${esc(item)}</div>`).join('')}</div>`:''}${group.children.map(child=>`<div class="map-subbranch"><div class="map-subtitle"><span>二级标题</span><b>${esc(child.label)}</b></div>${child.items.length?`<div class="map-details">${child.items.map(item=>`<div class="map-detail">${esc(item)}</div>`).join('')}</div>`:''}</div>`).join('')}</div></section>`).join('')}</div></div><span class="generated-at">结构与笔记目录保持一致 · ${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</span>`;
  if(showToast)toast('已按一级、二级标题更新思维导图');
}
function reviewCard(index,label,title,body,options={}){const source=options.time?`<button class="source-jump" data-time="${esc(options.time)}">回到 ${esc(options.time)} 的转写</button>`:'';return`<article class="review-card ${options.className||''}"><span class="card-index">${pad(index)}</span><div><p class="card-label">${esc(label)}</p><h3>${esc(trimText(title,54))}</h3><p>${esc(trimText(body,100))}</p>${source}</div></article>`}
function generateReview(showToast=true){
  updateCount();saveTranscript();const data=collectStudyData(),grid=$('#reviewGrid');
  if(data.all.join('').length<12){emptyGenerated(grid,'先写一点课堂笔记，或开始录音产生转写，再回来生成复习重点。');if(showToast)toast('先添加一些笔记或转写内容');return}
  const emphasis=findEmphasis(data),core=data.notes.find(keywordScore)||data.notes[0]||data.transcript[0]?.text||data.title;
  const question=data.notes.find(text=>/[？?]|为什么|如何|疑问|不懂/.test(text));
  const contrast=data.all.find(text=>/区别|相比|不同|但是|而是|分为/.test(text));
  grid.innerHTML=[
    reviewCard(1,'优先复习','老师强调的内容',emphasis?.text||core,{className:'priority',time:emphasis?.time}),
    reviewCard(2,'核心概念',core,contrast||'尝试脱离笔记，用自己的话复述这一点，并补充一个课堂例子。'),
    reviewCard(3,'待解决',question||`为什么“${data.title}”是这节课的核心？`,'回看相关笔记和转写，写出一句结论与一条理由。'),
    reviewCard(4,'自测题',`请概括“${data.title}”的核心观点`,'限时 2 分钟作答：先写结论，再列出两个支持要点。',{className:'question'})
  ].join('');
  if(showToast)toast('复习重点已根据当前内容更新');
}
function secondsFromTime(time){return String(time).split(':').reduce((total,part)=>total*60+Number(part),0)}
function jumpToTranscript(time){
  const classroom=$('.tab[data-view="classroom"]');classroom?.click();
  if(audio.src){audio.currentTime=Math.min(secondsFromTime(time),Number.isFinite(audio.duration)?audio.duration:state.recordedDuration||Infinity);timerEl.textContent=time}
  setTimeout(()=>{const target=[...$$('.transcript-block')].find(block=>block.dataset.time===time);target?.scrollIntoView({behavior:'smooth',block:'center'});target?.classList.add('highlight');setTimeout(()=>target?.classList.remove('highlight'),1400)},80);
}
$$('.tab').forEach(btn=>btn.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$(`#${btn.dataset.view}View`).classList.add('active');if(btn.dataset.view==='mindmap')generateMindmap(false);if(btn.dataset.view==='review')generateReview(false)});
$('#generateMindmap').onclick=()=>generateMindmap(true);$('#generateReview').onclick=()=>generateReview(true);
document.addEventListener('click',event=>{const btn=event.target.closest('.source-jump');if(btn?.dataset.time)jumpToTranscript(btn.dataset.time)});
$('#addCourse').onclick=()=>{const name=prompt('新课程名称');if(!name?.trim())return;const lesson={id:uid('lesson'),name:'第1节课'},course={id:uid('course'),name:name.trim(),open:true,lessons:[lesson]};state.courses.push(course);saveCourses();switchLesson(course.id,lesson.id);toast('课程已创建，可以点击标题重命名课时')};
$('.title-edit').onclick=()=>renameLesson(state.currentCourse,state.currentLesson);
ensureSelection();editor.querySelectorAll('.note-image').forEach(bindImage);bindTables();renderNoteOutline();renderTree();
updateCount();

// Allow supported AI clients to work with the same visible note-taking surface.
if(document.modelContext?.registerTool){
  const lifecycle=new AbortController();
  Promise.resolve(document.modelContext.registerTool({
    name:'add_class_note',title:'添加课堂笔记',description:'把一段文字追加到当前课时的个人笔记中，可附带当前录音时间。',
    inputSchema:{type:'object',properties:{text:{type:'string',minLength:1},withTimestamp:{type:'boolean'}},required:['text'],additionalProperties:false},
    annotations:{readOnlyHint:false,untrustedContentHint:false},
    execute(input){if(!input||typeof input.text!=='string'||!input.text.trim())throw new Error('笔记内容不能为空');const stamp=input.withTimestamp?`<span style="color:#6179d1;font:600 12px Inter">${formatTime(state.seconds)}</span>　`:'';insertHtml(`<p>${stamp}${input.text.replace(/[<>]/g,'')}</p>`);return{lesson:$('#lessonTitle').textContent,added:true,time:formatTime(state.seconds)}}
  },{signal:lifecycle.signal})).catch(()=>{});
  Promise.resolve(document.modelContext.registerTool({
    name:'mark_distraction',title:'标记走神位置',description:'在当前录音时间插入一条走神标记，方便课后回听。',
    inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},
    execute(){if(!state.recording)throw new Error('当前没有正在进行的录音');$('#lostBtn').click();return{marked:true,time:formatTime(state.seconds)}}
  },{signal:lifecycle.signal})).catch(()=>{});
}
